# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ext_nb_to_list <- function(nbd_list, g) {
    .Call(`_SGFLMMBayesian_ext_nb_to_list`, nbd_list, g)
}

ext_list_to_mat <- function(temp, g) {
    .Call(`_SGFLMMBayesian_ext_list_to_mat`, temp, g)
}

ext_list_to_vec <- function(temp, g) {
    .Call(`_SGFLMMBayesian_ext_list_to_vec`, temp, g)
}

DiagMat <- function(n) {
    .Call(`_SGFLMMBayesian_DiagMat`, n)
}

dlaplaceArma <- function(x, location, scale, log = FALSE) {
    .Call(`_SGFLMMBayesian_dlaplaceArma`, x, location, scale, log)
}

dnormArma <- function(x, mean, sd, log = FALSE) {
    .Call(`_SGFLMMBayesian_dnormArma`, x, mean, sd, log)
}

dmvnormArma <- function(x, mean, sigma) {
    .Call(`_SGFLMMBayesian_dmvnormArma`, x, mean, sigma)
}

dnormArmaVec <- function(betaj, mu, sigma, log = FALSE) {
    .Call(`_SGFLMMBayesian_dnormArmaVec`, betaj, mu, sigma, log)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_SGFLMMBayesian_mvrnormArma`, n, mu, sigma)
}

rtruncnormRcpp <- function(n, a, b, mean, sd) {
    .Call(`_SGFLMMBayesian_rtruncnormRcpp`, n, a, b, mean, sd)
}

dinvgammaArma <- function(x, shape, scale, take_log) {
    .Call(`_SGFLMMBayesian_dinvgammaArma`, x, shape, scale, take_log)
}

rinvgammaArma <- function(n, shape, scale) {
    .Call(`_SGFLMMBayesian_rinvgammaArma`, n, shape, scale)
}

cell2nb_rcpp <- function(nrow, ncol, torus = 0L) {
    .Call(`_SGFLMMBayesian_cell2nb_rcpp`, nrow, ncol, torus)
}

s1s2_rcpp <- function(nbd_index, data) {
    .Call(`_SGFLMMBayesian_s1s2_rcpp`, nbd_index, data)
}

gibbsSampling_dd <- function(sub_nbd_index, sub_Xstar, alpha, betaj, eta, u_g, ini_data, M) {
    .Call(`_SGFLMMBayesian_gibbsSampling_dd`, sub_nbd_index, sub_Xstar, alpha, betaj, eta, u_g, ini_data, M)
}

neg_SAE_dd <- function(sub_nbd_index, sub_Xstar, sub_data, eta_current, alpha_current, betaj_current, u_g, s1s2) {
    .Call(`_SGFLMMBayesian_neg_SAE_dd`, sub_nbd_index, sub_Xstar, sub_data, eta_current, alpha_current, betaj_current, u_g, s1s2)
}

u_DMH_dd <- function(subX, sub_data, sub_nbd_index, p, basis, eta_current, alpha_current, betaj_current, u_g_current, sigmau_squ, s_vec, M_auxz) {
    .Call(`_SGFLMMBayesian_u_DMH_dd`, subX, sub_data, sub_nbd_index, p, basis, eta_current, alpha_current, betaj_current, u_g_current, sigmau_squ, s_vec, M_auxz)
}

fixed_DMH_dd <- function(subX, sub_data, sub_nbd_index, p, basis, eta_current, eta_proposed, alpha_current, alpha_proposed, betaj_current, betaj_proposed, u_g_current, M_auxz) {
    .Call(`_SGFLMMBayesian_fixed_DMH_dd`, subX, sub_data, sub_nbd_index, p, basis, eta_current, eta_proposed, alpha_current, alpha_proposed, betaj_current, betaj_proposed, u_g_current, M_auxz)
}

ii_fun <- function(Xstar, data, alpha, betaj) {
    .Call(`_SGFLMMBayesian_ii_fun`, Xstar, data, alpha, betaj)
}

gibbsSampling_id <- function(nbd_index, Xstar, alpha, betaj, eta, ini_data, M) {
    .Call(`_SGFLMMBayesian_gibbsSampling_id`, nbd_index, Xstar, alpha, betaj, eta, ini_data, M)
}

neg_SAE_id <- function(nbd_index, Xstar, data, eta_current, alpha_current, betaj_current, s1s2) {
    .Call(`_SGFLMMBayesian_neg_SAE_id`, nbd_index, Xstar, data, eta_current, alpha_current, betaj_current, s1s2)
}

fixed_DMH_id <- function(nbd_index, Xstar, data, eta_current, eta_proposed, alpha_current, alpha_proposed, betaj_current, betaj_proposed, M_auxz) {
    .Call(`_SGFLMMBayesian_fixed_DMH_id`, nbd_index, Xstar, data, eta_current, eta_proposed, alpha_current, alpha_proposed, betaj_current, betaj_proposed, M_auxz)
}

fixed_di_fun <- function(subX, sub_data, basis, alpha, betaj, u_g) {
    .Call(`_SGFLMMBayesian_fixed_di_fun`, subX, sub_data, basis, alpha, betaj, u_g)
}

u_MH_di <- function(subX, sub_data, basis, alpha_current, betaj_current, u_g_current, sigmau_squ, s_vec, M_auxz) {
    .Call(`_SGFLMMBayesian_u_MH_di`, subX, sub_data, basis, alpha_current, betaj_current, u_g_current, sigmau_squ, s_vec, M_auxz)
}

rw_dd <- function(M, initial, tune_fixed, tune_sigmau2, tune_u, autotune, true_X, data, nbd_list, p, basis, M_auxz, G, prior_a, prior_b) {
    .Call(`_SGFLMMBayesian_rw_dd`, M, initial, tune_fixed, tune_sigmau2, tune_u, autotune, true_X, data, nbd_list, p, basis, M_auxz, G, prior_a, prior_b)
}

rw_di <- function(M, initial, tune_fixed, tune_sigmau2, tune_u, autotune, true_X, data, p, basis, M_auxz, G, prior_a, prior_b) {
    .Call(`_SGFLMMBayesian_rw_di`, M, initial, tune_fixed, tune_sigmau2, tune_u, autotune, true_X, data, p, basis, M_auxz, G, prior_a, prior_b)
}

rw_id <- function(M, initial, tune_fixed, autotune, nbd_index, Xstar, data_vec, p, M_auxz) {
    .Call(`_SGFLMMBayesian_rw_id`, M, initial, tune_fixed, autotune, nbd_index, Xstar, data_vec, p, M_auxz)
}

rw_ii <- function(M, initial, tune_fixed, autotune, Xstar, data_vec, p) {
    .Call(`_SGFLMMBayesian_rw_ii`, M, initial, tune_fixed, autotune, Xstar, data_vec, p)
}

varArma <- function(tau, rho, Dv, nbd_mat) {
    .Call(`_SGFLMMBayesian_varArma`, tau, rho, Dv, nbd_mat)
}

estX_fun_k <- function(M, Xstar_trun, Dv, nbd_mat, initial, S_tau, S_rho, autotune) {
    .Call(`_SGFLMMBayesian_estX_fun_k`, M, Xstar_trun, Dv, nbd_mat, initial, S_tau, S_rho, autotune)
}

estX_fun_k_w_mu <- function(M, Xstar_trun, Dv, nbd_mat, initial, S_tau, S_rho, autotune) {
    .Call(`_SGFLMMBayesian_estX_fun_k_w_mu`, M, Xstar_trun, Dv, nbd_mat, initial, S_tau, S_rho, autotune)
}

